apiVersion: v1
kind: Service
metadata:
  name: nodejs-restapi-seed-service
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 3000
      protocol: TCP
  selector:
    app: nodejs-restapi-seed
