apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-restapi-seed-deployment
spec:
  selector:
    matchLabels:
      app: nodejs-restapi-seed
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-restapi-seed
    spec:
      containers:
        - name: nodejs-restapi-seed
          image: danieldelgado/nodejs-restapi-seed:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PRODUCTION
              value: "true"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database
                  key: db_host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: db_password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database
                  key: db_name
